// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clrrbndkhaekssldrdwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNscnJibmRraGFla3NzbGRyZHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDg5MDMsImV4cCI6MjA3MDIyNDkwM30.LNpalq-X2-CsULgc-WrlJXCuSQObIIcUXRIXY1XHpf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});